version: '3.8'

services:
  auth-service:
    build: ./services/auth-service
    ports:
      - "3001:3001"
    env_file:
      - ./services/auth-service/.env

  market-data-service:
    build: ./services/market-data-service
    ports:
      - "3002:3002"
    env_file:
      - ./services/market-data-service/.env

  user-profile-service:
    build: ./services/user-profile-service
    ports:
      - "3003:3003"
    env_file:
      - ./services/user-profile-service/.env
